FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir streamlit pyhive pandas plotly thrift thrift-sasl

# COPY streamlit/app.py /app/app.py

# Expose the default Streamlit port
EXPOSE 8501

# Use CMD to run the Streamlit application
# CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]